[project]
name = "repl-nix-wp-support-ticket-system"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "streamlit-quill>=0.0.3",
    "streamlit>=1.40.2",
]
